version: '3.3'
services:
  golang:
    build:
      context: ./golang
      dockerfile: Dockerfile
    container_name: golang
    ports:
      - 8080:8080
  varnish:
    build:
      context: ./varnish
      dockerfile: Dockerfile
    container_name: varnish
    tmpfs:
      - /usr/local/var/varnish:exec
    ports:
      - 8081:80
